name = "ink-auth-api"
main = "auth-worker.js"
compatibility_date = "2023-10-30"

# 环境变量配置 (敏感信息需在 Cloudflare 后台设置)
[vars]
ENVIRONMENT = "production"

# 敏感环境变量需要通过 wrangler secret 命令或 Cloudflare Dashboard 设置:
# PASSWORD_1 = "your-secret-password-1"
# PASSWORD_2 = "your-secret-password-2" 
# JWT_SECRET = "your-jwt-secret-key"
# PROTECTED_LINK_1 = "your-protected-link-1"
# PROTECTED_LINK_2 = "your-protected-link-2"